### ISSUE TITLE
Formato HTML

### ISSUE THREAD

**Issue by arturfelipe** [eduardocereto/pyboleto#24]
Geração de boletos em HTML.

**Comment by eduardocereto** [comment]
Acabei de fazer um merge do repositório da Tracy Web pra dentro do merge de development. Ainda tem que escrever uns testes e melhorar o código. 

https://github.com/eduardocereto/pyboleto/commit/b63e84478389c89804fcf2a03363f338cb2d1ee2

**Comment by eduardocereto** [comment]
closed in 7201d45648b6dfee27a3115bcf30ca55ee130644

**Comment by seocam** [comment]
@eduardocereto valeu! Nós devemos ter um tempo em breve pra melhorar o código.

**Comment by eduardocereto** [comment]
@seocam 
Eu fiz algumas modificações antes de importar o branch de vocês. 

Então se puderem syncar vai ficar mais facil fazer merges no futuro.
