### ISSUE TITLE
Homologação Caixa

### ISSUE THREAD

**Issue by upmauro** [eduardocereto/pyboleto#40]
Estou passando pela homologação da caixa para os boletos não registrados.

Segue algumas observações, que impediram a homologação. Espero em breve fazer o pull request.

Campo Beneficiário
Conteúdo Atual: Cedente
Conteúdo Esperado: Beneficiário

Campo Instruções
Conteúdo Atual: Instruções
Conteúdo Esperado: Instruções (Texto de Responsabilidade do Beneficiário)

Campo Agência / Código Beneficiário
Conteúdo Atual: Agência/Código cedente
Conteúdo Esperado: Agência / Código Beneficiário

**Comment by eduardocereto** [comment]
Fixed on 0.3.1
