### ISSUE TITLE
Documentação em Português ou Inglês?

### ISSUE THREAD

**Issue by eduardocereto** [eduardocereto/pyboleto#5]
Originalmente eu estava escrevendo toda a documentação em Inglês. Mas agora resolvi mudar para escrever em Português e deixar apenas o README do repositório em Inglês. O que vocês preferem?

**Comment by hernandesbsousa** [comment]
@eduardocereto I am discussing an issue exactly like this with the team in my workplace for private repositories. Other than contributions from non-portuguese speakers, do you have more points regarding this help me enrich the debate?

Thanks!
