### ISSUE TITLE
PDF mode carnê

### ISSUE THREAD

**Issue by eluizbr** [eduardocereto/pyboleto#51]
Amigos,

Como faço para gerar 2 boletos nas mesma paginas?

Estou fazendo assim para imprimir em uma pagina:  https://gist.github.com/eluizbr/df9a4b8adf8a9d9ca746

Obrigado prla ajuda

**Comment by eduardocereto** [comment]
O métodos `drawBoletoCarneDuplo` imprime em modo carne. Me parece que voce ja esta usando ele.
