### ISSUE TITLE
Erro no uso de Decimal() no Python 3.4

### ISSUE THREAD

**Issue by arqeco** [eduardocereto/pyboleto#52]
No python 3.4 o pyboleto está apresentando um erro afirmando que o argumento opcional da função Decimal deve ser um contexto. Por exemplo, abaixo está o final do resultado de "python setup.py test".

    ======================================================================
    ERROR: test_nosso_numero (tests.test_banco_santander.TestBancoSantander)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "c:\temp\boleto2\pyboleto\build\lib\tests\test_banco_santander.py", line 20, in setUp
        d.valor_documento = 2952.95
      File "c:\temp\boleto2\pyboleto\build\lib\pyboleto\data.py", line 328, in _set_valor_documento
        self._valor_documento = Decimal(str(val), 2)
    TypeError: optional argument must be a context
    
    ----------------------------------------------------------------------
    Ran 111 tests in 0.690s
    
    FAILED (errors=35, skipped=47)

Aqui em http://stackoverflow.com/questions/13194384/instantiate-decimal-class se discute um pouco sobre esta questão.

**Comment by eduardocereto** [comment]
Getting fixed on v0.3
