### ISSUE TITLE
Retornar valores gerados pela pyboleto

### ISSUE THREAD

**Issue by rafaeltardivo** [eduardocereto/pyboleto#64]
Pessoal, bom dia.

Vocês veem algum problema em retornar valores gerados na pyboleto? (como DV do barcode, por exemplo). Vou precisar desses valores e se não for algo que atrapalhe  ou gere alguma vulnerabilidade na biblioteca, já subo pra Pyboleto tbm...

**Comment by mojimi** [comment]
@rafaeltardivo amigo, dei uma rápida olhada no código fonte, e tem a função "calculate_dv_barcode" na superclasse dos boletos
