### ISSUE TITLE
Duvidas geração de boletos Bradesco

### ISSUE THREAD

**Issue by gbrennon** [eduardocereto/pyboleto#67]
Estou trabalhando no desenvolvimento de um sistema e estou utilizando o pyboleto para gerar os boletos para o banco Bradesco.

Eu já consigo gerar boletos de exemplo, porém ainda tenho dúvidas com algumas etapas no processo de pagamento.

Quais valores eu insiro no campo "Nosso numero"?
E o "Numero documento", ele tem alguma regra para ser gerado?

Após o boleto ser gerado, existe algum processo a ser executado para registrar o boleto com o banco ou esse boleto ja esta 100% válido?

Meu cliente questionou que, caso o boleto não seja validado com o banco, uma taxa adicional será paga.

Aguardo retorno!

**Comment by eduardocereto** [comment]
Recomendo olhar a documentação do banco no que diz respeito a gerar o nosso numero e numero do documento. 

O boleto gerado pelo sistema não é "automaticamente registrado", você precisa entrar em contato com o banco para se informar de como registrar o boleto para pagamento. Antigamente os boletos não precisavam ser registrados, com as leis novas todos os boletos devem ser registrados com o banco, pelo bradesco isso é feito com o envio de arquivos de remessa com os boletos que são gerados. Esta etapa esta fora do escopo do projeto.
