### ISSUE TITLE
Boleto Registrado

### ISSUE THREAD

**Issue by djpremier** [eduardocereto/pyboleto#69]
Eae algo a respeito do registro dos boletos? A biblioteca é muito boa, mas vai se tornar quase que inútil se isso não for realizado, alguém já começou? Posso ajudar a desenvolver.

**Comment by eduardocereto** [comment]
Eu tenho gerado boletos registrados sem problemas, boletos registrados são praticamente idênticos a boletos não registrados, geralmente só existe uma mudança de carteira, e obviamente o requisito de enviar as informações do boleto gerado para o banco. O que a biblioteca faz é gerar os boletos. Não existem planos de gerar arquivos de remessa ou processar arquivos de retorno, esta fora do escopo do projeto. Se tiver problemas em gerar boleto registrado para algum banco favor incluir detalhes.
